version: '3.4'


services:
  nginx:
    container_name: nginx
    restart: on-failure
    image: nginx
    links:
      - core
    depends_on:
      - core
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  core:
    container_name: core
    build:
      context: ./core
    volumes:
      - ./core:/service
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - NOTES_SECRET_KEY
      - NOTES_DB_NAME

  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=NOTES_DB_NAME
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
