version: '3.4'


services:
  core:
    container_name: core
    build:
      context: ./core
    volumes:
      - ./core:/service
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - NOTES_SECRET_KEY
      - NOTES_DB_NAME
    ports:
      - 127.0.0.1:8000:8000  # django port
      - 127.0.0.1:5678:5678  # debug port

  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=NOTES_DB_NAME
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
