version: '3.9'


services:
  nginx:
    container_name: nginx
    restart: on-failure
    image: nginx
    links:
      - core
    depends_on:
      - core
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webui/build:/usr/share/nginx/html:ro


  core:
    container_name: core
    build:
      context: ./core
    volumes:
      - ./core:/service
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_PASSWORD
      - NOTES_SECRET_KEY
      - NOTES_DB_NAME
    command: "gunicorn --reload -b 0.0.0.0:80 -w 4 mysite.wsgi"

  core-prepare:
    container_name: core-prepare
    build:
      context: ./core
    volumes:
      - ./core:/service
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_PASSWORD
      - NOTES_SECRET_KEY
      - NOTES_DB_NAME
    command: bash -c "./manage.py makemigrations && ./manage.py migrate"
    profiles:
      - prepare

  build-webui:
    container_name: build-webui
    build:
      context: ./webui
    volumes:
      - ./webui:/service
    profiles:
      - prepare

  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_USER=${NOTES_DB_NAME}
      - POSTGRES_PASSWORD
      - POSTGRES_DB=${NOTES_DB_NAME}
    volumes:
      - ${NOTES_PGDATA_PATH}:/var/lib/postgresql/data
